blank_issues_enabled: true
contact_links:
  - name: Questions & Discussions
    url: https://github.com/YOUR_USERNAME/rateuni/discussions
    about: Ask questions and discuss ideas with the community
